# Generated by Django 5.1.6 on 2025-08-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tipoatributo_subcategoria_producto_subcategoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributoproducto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
