# Generated by Django 5.1.6 on 2025-08-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_atributoproducto_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='es_tendencia',
        ),
    ]
