# Generated by Django 5.1.6 on 2025-11-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_producto_descuento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
